
<script type="text/javascript">
//<![CDATA[
    function initFatZebra() {
     //   if (!document.getElementById("row_payment_fatzebra_title")) {
            // Don't perform for website and store view
      //      return;
        //}
		$('payment_fatzebra').insert('<span style="display: block; line-height: 103px; background: #EAF0EE; border: 1px solid #CCCCCC; margin-bottom: 10px; padding: 0px 0 0 10px; margin-top: 10px;"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/payments/mindarc.png" border="0" style="float: left; margin: 10px 20px 0 10px;"/> Built by <a href="http://www.mindarc.com.au" target="_blank">www.mindarc.com.au</a></span>');
    }
//]]>
</script>
